const Products ={  
  "id":"shop/new/all-new",
  "name":"All New",
  "categoryType":"subcat",
  "groups":[  
    {  
      "id":"belgian-flax-linen-graduated-stripe-duvet-cover-shams-b2565",
      "name":"Belgian Flax Linen Graduated Stripe Duvet Cover + Shams",
      "links":{  
        "www":"https://www.westelm.com/products/belgian-flax-linen-graduated-stripe-duvet-cover-shams-b2565/"
      },
      "priceRange":{  
        "selling":{  
          "high":229,
          "low":39
        }
      },
      "thumbnail":{  
        "size":"m",
        "meta":"",
        "alt":"",
        "rel":"thumbnail",
        "width":363,
        "href":"https://www.westelm.com/weimgs/rk/images/wcm/products/201843/0007/belgian-flax-linen-graduated-stripe-duvet-cover-shams-1-m.jpg",
        "height":363
      },
      "hero":{  
        "size":"m",
        "meta":"",
        "alt":"",
        "rel":"hero",
        "width":363,
        "href":"https://www.westelm.com/weimgs/rk/images/wcm/products/201843/0007/belgian-flax-linen-graduated-stripe-duvet-cover-shams-1-m.jpg",
        "height":363
      },
      "images":[  
        {  
          "size":"m",
          "meta":"",
          "alt":"",
          "rel":"althero",
          "width":363,
          "href":"https://www.westelm.com/weimgs/rk/images/wcm/products/201843/0007/belgian-flax-linen-graduated-stripe-duvet-cover-shams-m.jpg",
          "height":363
        }
      ],
      "swatches":[  

      ],
      "messages":[  
        "Use Code SAVEMORE At Checkout"
      ],
      "flags":[  
        {  
          "bopisSuppress":false,
          "rank":3,
          "id":"newcore"
        },
        {  
          "bopisSuppress":false,
          "rank":4,
          "id":"freeship"
        },
        {  
          "bopisSuppress":false,
          "rank":9,
          "id":"fairTrade"
        }
      ],
      "reviews":{  
        "recommendationCount":0,
        "likelihood":0,
        "reviewCount":0,
        "averageRating":0,
        "id":"belgian-flax-linen-graduated-stripe-duvet-cover-shams-b2565",
        "type":"GROUP_REVIEWS"
      }
    },
    {  
      "id":"belgian-flax-linen-melange-duvet-cover-shams-pale-lilac-b2566",
      "name":"Belgian Flax Linen Melange Duvet Cover + Shams - Pale Lilac",
      "links":{  
        "www":"https://www.westelm.com/products/belgian-flax-linen-melange-duvet-cover-shams-pale-lilac-b2566/"
      },
      "priceRange":{  
        "selling":{  
          "high":249,
          "low":44
        }
      },
      "thumbnail":{  
        "size":"m",
        "meta":"",
        "alt":"",
        "rel":"thumbnail",
        "width":363,
        "href":"https://www.westelm.com/weimgs/rk/images/wcm/products/201843/0007/belgian-flax-linen-melange-duvet-cover-shams-m.jpg",
        "height":363
      },
      "hero":{  
        "size":"m",
        "meta":"",
        "alt":"",
        "rel":"hero",
        "width":363,
        "href":"https://www.westelm.com/weimgs/rk/images/wcm/products/201843/0007/belgian-flax-linen-melange-duvet-cover-shams-m.jpg",
        "height":363
      },
      "images":[  
        {  
          "size":"m",
          "meta":"",
          "alt":"",
          "rel":"althero",
          "width":363,
          "href":"https://www.westelm.com/weimgs/rk/images/wcm/products/201843/0007/belgian-flax-linen-melange-duvet-cover-shams-2-m.jpg",
          "height":363
        }
      ],
      "swatches":[  

      ],
      "messages":[  
        "Use Code SAVEMORE At Checkout"
      ],
      "flags":[  
        {  
          "bopisSuppress":false,
          "rank":4,
          "id":"freeship"
        },
        {  
          "bopisSuppress":false,
          "rank":9,
          "id":"fairTrade"
        },
        {  
          "bopisSuppress":false,
          "rank":11,
          "id":"new_colors"
        }
      ],
      "reviews":{  
        "recommendationCount":0,
        "likelihood":0,
        "reviewCount":0,
        "averageRating":0,
        "id":"belgian-flax-linen-melange-duvet-cover-shams-pale-lilac-b2566",
        "type":"GROUP_REVIEWS"
      }
    },
    {  
      "id":"belgian-flax-linen-fiber-dyed-duvet-cover-shams-indigo-b2567",
      "name":"Belgian Flax Linen Fiber Dyed Duvet Cover + Shams - Indigo",
      "links":{  
        "www":"https://www.westelm.com/products/belgian-flax-linen-fiber-dyed-duvet-cover-shams-indigo-b2567/"
      },
      "priceRange":{  
        "selling":{  
          "high":249,
          "low":44
        }
      },
      "thumbnail":{  
        "size":"m",
        "meta":"",
        "alt":"",
        "rel":"thumbnail",
        "width":363,
        "href":"https://www.westelm.com/weimgs/rk/images/wcm/products/201843/0007/belgian-flax-linen-fiber-dyed-duvet-cover-shams-3-m.jpg",
        "height":363
      },
      "hero":{  
        "size":"m",
        "meta":"",
        "alt":"",
        "rel":"hero",
        "width":363,
        "href":"https://www.westelm.com/weimgs/rk/images/wcm/products/201843/0007/belgian-flax-linen-fiber-dyed-duvet-cover-shams-3-m.jpg",
        "height":363
      },
      "images":[  
        {  
          "size":"m",
          "meta":"",
          "alt":"",
          "rel":"althero",
          "width":363,
          "href":"https://www.westelm.com/weimgs/rk/images/wcm/products/201843/0007/belgian-flax-linen-fiber-dyed-duvet-cover-shams-2-m.jpg",
          "height":363
        }
      ],
      "swatches":[  

      ],
      "messages":[  
        "Use Code SAVEMORE At Checkout"
      ],
      "flags":[  
        {  
          "bopisSuppress":false,
          "rank":4,
          "id":"freeship"
        },
        {  
          "bopisSuppress":false,
          "rank":9,
          "id":"fairTrade"
        },
        {  
          "bopisSuppress":false,
          "rank":11,
          "id":"new_colors"
        }
      ],
      "reviews":{  
        "recommendationCount":0,
        "likelihood":0,
        "reviewCount":0,
        "averageRating":0,
        "id":"belgian-flax-linen-fiber-dyed-duvet-cover-shams-indigo-b2567",
        "type":"GROUP_REVIEWS"
      }
    },
    {  
      "id":"belgian-flax-linen-fiber-dyed-duvet-cover-shams-frost-gray-b2568",
      "name":"Belgian Flax Linen Fiber Dyed Duvet Cover + Shams - Frost Gray",
      "links":{  
        "www":"https://www.westelm.com/products/belgian-flax-linen-fiber-dyed-duvet-cover-shams-frost-gray-b2568/"
      },
      "priceRange":{  
        "selling":{  
          "high":249,
          "low":44
        }
      },
      "thumbnail":{  
        "size":"m",
        "meta":"",
        "alt":"",
        "rel":"thumbnail",
        "width":363,
        "href":"https://www.westelm.com/weimgs/rk/images/wcm/products/201843/0007/belgian-flax-linen-fiber-dyed-duvet-cover-shams-frost-gray-m.jpg",
        "height":363
      },
      "hero":{  
        "size":"m",
        "meta":"",
        "alt":"",
        "rel":"hero",
        "width":363,
        "href":"https://www.westelm.com/weimgs/rk/images/wcm/products/201843/0007/belgian-flax-linen-fiber-dyed-duvet-cover-shams-frost-gray-m.jpg",
        "height":363
      },
      "images":[  
        {  
          "size":"m",
          "meta":"",
          "alt":"",
          "rel":"althero",
          "width":363,
          "href":"https://www.westelm.com/weimgs/rk/images/wcm/products/201843/0007/belgian-flax-linen-fiber-dyed-duvet-cover-shams-1-m.jpg",
          "height":363
        }
      ],
      "swatches":[  

      ],
      "messages":[  
        "Use Code SAVEMORE At Checkout"
      ],
      "flags":[  
        {  
          "bopisSuppress":false,
          "rank":4,
          "id":"freeship"
        },
        {  
          "bopisSuppress":false,
          "rank":9,
          "id":"fairTrade"
        },
        {  
          "bopisSuppress":false,
          "rank":11,
          "id":"new_colors"
        }
      ],
      "reviews":{  
        "recommendationCount":0,
        "likelihood":0,
        "reviewCount":0,
        "averageRating":0,
        "id":"belgian-flax-linen-fiber-dyed-duvet-cover-shams-frost-gray-b2568",
        "type":"GROUP_REVIEWS"
      }
    },
    {  
      "id":"tencel-cotton-matelasse-duvet-cover-shams-stormy-blue-b2570",
      "name":"TENCEL&#8482; Cotton Matelasse Duvet Cover + Shams - Stormy Blue",
      "links":{  
        "www":"https://www.westelm.com/products/tencel-cotton-matelasse-duvet-cover-shams-stormy-blue-b2570/"
      },
      "priceRange":{  
        "selling":{  
          "high":209,
          "low":44
        }
      },
      "thumbnail":{  
        "size":"m",
        "meta":"",
        "alt":"",
        "rel":"thumbnail",
        "width":363,
        "href":"https://www.westelm.com/weimgs/rk/images/wcm/products/201843/0007/tencel-cotton-matelasse-duvet-cover-shams-stormy-blue-m.jpg",
        "height":363
      },
      "hero":{  
        "size":"m",
        "meta":"",
        "alt":"",
        "rel":"hero",
        "width":363,
        "href":"https://www.westelm.com/weimgs/rk/images/wcm/products/201843/0007/tencel-cotton-matelasse-duvet-cover-shams-stormy-blue-m.jpg",
        "height":363
      },
      "images":[  
        {  
          "size":"m",
          "meta":"",
          "alt":"",
          "rel":"althero",
          "width":363,
          "href":"https://www.westelm.com/weimgs/rk/images/wcm/products/201843/0007/tencel-cotton-matelasse-duvet-cover-shams-m.jpg",
          "height":363
        }
      ],
      "swatches":[  

      ],
      "messages":[  
        "Use Code SAVEMORE At Checkout"
      ],
      "flags":[  
        {  
          "bopisSuppress":false,
          "rank":3,
          "id":"newcore"
        },
        {  
          "bopisSuppress":false,
          "rank":4,
          "id":"freeship"
        },
        {  
          "bopisSuppress":false,
          "rank":8,
          "id":"handmade"
        },
        {  
          "bopisSuppress":false,
          "rank":9,
          "id":"fairTrade"
        }
      ],
      "reviews":{  
        "recommendationCount":0,
        "likelihood":0,
        "reviewCount":0,
        "averageRating":0,
        "id":"tencel-cotton-matelasse-duvet-cover-shams-stormy-blue-b2570",
        "type":"GROUP_REVIEWS"
      }
    },
    {  
      "id":"tencel-cotton-matelasse-duvet-cover-shams-stone-white-b2571",
      "name":"TENCEL&#8482; Cotton Matelasse Duvet Cover + Shams - Stone White",
      "links":{  
        "www":"https://www.westelm.com/products/tencel-cotton-matelasse-duvet-cover-shams-stone-white-b2571/"
      },
      "priceRange":{  
        "selling":{  
          "high":209,
          "low":44
        }
      },
      "thumbnail":{  
        "size":"m",
        "meta":"",
        "alt":"",
        "rel":"thumbnail",
        "width":363,
        "href":"https://www.westelm.com/weimgs/rk/images/wcm/products/201843/0007/tencel-cotton-matelasse-duvet-cover-shams-stone-white-m.jpg",
        "height":363
      },
      "hero":{  
        "size":"m",
        "meta":"",
        "alt":"",
        "rel":"hero",
        "width":363,
        "href":"https://www.westelm.com/weimgs/rk/images/wcm/products/201843/0007/tencel-cotton-matelasse-duvet-cover-shams-stone-white-m.jpg",
        "height":363
      },
      "images":[  
        {  
          "size":"m",
          "meta":"",
          "alt":"",
          "rel":"althero",
          "width":363,
          "href":"https://www.westelm.com/weimgs/rk/images/wcm/products/201843/0007/tencel-cotton-matelasse-duvet-cover-shams-stone-white-1-m.jpg",
          "height":363
        }
      ],
      "swatches":[  

      ],
      "messages":[  
        "Use Code SAVEMORE At Checkout"
      ],
      "flags":[  
        {  
          "bopisSuppress":false,
          "rank":3,
          "id":"newcore"
        },
        {  
          "bopisSuppress":false,
          "rank":4,
          "id":"freeship"
        },
        {  
          "bopisSuppress":false,
          "rank":8,
          "id":"handmade"
        },
        {  
          "bopisSuppress":false,
          "rank":9,
          "id":"fairTrade"
        }
      ],
      "reviews":{  
        "recommendationCount":0,
        "likelihood":0,
        "reviewCount":0,
        "averageRating":0,
        "id":"tencel-cotton-matelasse-duvet-cover-shams-stone-white-b2571",
        "type":"GROUP_REVIEWS"
      }
    },
    {  
      "id":"tencel-cotton-matelasse-duvet-cover-shams-blue-teal-b2572",
      "name":"TENCEL&#8482; Cotton Matelasse Duvet Cover + Shams - Blue Teal",
      "links":{  
        "www":"https://www.westelm.com/products/tencel-cotton-matelasse-duvet-cover-shams-blue-teal-b2572/"
      },
      "priceRange":{  
        "selling":{  
          "high":209,
          "low":44
        }
      },
      "thumbnail":{  
        "size":"m",
        "meta":"",
        "alt":"",
        "rel":"thumbnail",
        "width":363,
        "href":"https://www.westelm.com/weimgs/rk/images/wcm/products/201843/0007/tencel-cotton-matelasse-duvet-cover-shams-blue-teal-m.jpg",
        "height":363
      },
      "hero":{  
        "size":"m",
        "meta":"",
        "alt":"",
        "rel":"hero",
        "width":363,
        "href":"https://www.westelm.com/weimgs/rk/images/wcm/products/201843/0007/tencel-cotton-matelasse-duvet-cover-shams-blue-teal-m.jpg",
        "height":363
      },
      "images":[  
        {  
          "size":"m",
          "meta":"",
          "alt":"",
          "rel":"althero",
          "width":363,
          "href":"https://www.westelm.com/weimgs/rk/images/wcm/products/201843/0007/tencel-cotton-matelasse-duvet-cover-shams-blue-teal-1-m.jpg",
          "height":363
        }
      ],
      "swatches":[  

      ],
      "messages":[  
        "Use Code SAVEMORE At Checkout"
      ],
      "flags":[  
        {  
          "bopisSuppress":false,
          "rank":3,
          "id":"newcore"
        },
        {  
          "bopisSuppress":false,
          "rank":4,
          "id":"freeship"
        },
        {  
          "bopisSuppress":false,
          "rank":8,
          "id":"handmade"
        },
        {  
          "bopisSuppress":false,
          "rank":9,
          "id":"fairTrade"
        }
      ],
      "reviews":{  
        "recommendationCount":0,
        "likelihood":0,
        "reviewCount":0,
        "averageRating":0,
        "id":"tencel-cotton-matelasse-duvet-cover-shams-blue-teal-b2572",
        "type":"GROUP_REVIEWS"
      }
    },
    {  
      "id":"tencel-cotton-matelasse-duvet-cover-shams-pink-blush-b2573",
      "name":"TENCEL&#8482; Cotton Matelasse Duvet Cover + Shams - Pink Blush",
      "links":{  
        "www":"https://www.westelm.com/products/tencel-cotton-matelasse-duvet-cover-shams-pink-blush-b2573/"
      },
      "priceRange":{  
        "selling":{  
          "high":209,
          "low":44
        }
      },
      "thumbnail":{  
        "size":"m",
        "meta":"",
        "alt":"",
        "rel":"thumbnail",
        "width":363,
        "href":"https://www.westelm.com/weimgs/rk/images/wcm/products/201843/0007/tencel-cotton-matelasse-duvet-cover-shams-pink-blush-m.jpg",
        "height":363
      },
      "hero":{  
        "size":"m",
        "meta":"",
        "alt":"",
        "rel":"hero",
        "width":363,
        "href":"https://www.westelm.com/weimgs/rk/images/wcm/products/201843/0007/tencel-cotton-matelasse-duvet-cover-shams-pink-blush-m.jpg",
        "height":363
      },
      "images":[  
        {  
          "size":"m",
          "meta":"",
          "alt":"",
          "rel":"althero",
          "width":363,
          "href":"https://www.westelm.com/weimgs/rk/images/wcm/products/201843/0007/tencel-cotton-matelasse-duvet-cover-shams-pink-blush-1-m.jpg",
          "height":363
        }
      ],
      "swatches":[  

      ],
      "messages":[  
        "Use Code SAVEMORE At Checkout"
      ],
      "flags":[  
        {  
          "bopisSuppress":false,
          "rank":3,
          "id":"newcore"
        },
        {  
          "bopisSuppress":false,
          "rank":4,
          "id":"freeship"
        },
        {  
          "bopisSuppress":false,
          "rank":8,
          "id":"handmade"
        },
        {  
          "bopisSuppress":false,
          "rank":9,
          "id":"fairTrade"
        }
      ],
      "reviews":{  
        "recommendationCount":0,
        "likelihood":0,
        "reviewCount":0,
        "averageRating":0,
        "id":"tencel-cotton-matelasse-duvet-cover-shams-pink-blush-b2573",
        "type":"GROUP_REVIEWS"
      }
    },
    {  
      "id":"candlewick-duvet-cover-shams-b2574",
      "name":"Candlewick Duvet Cover + Shams",
      "links":{  
        "www":"https://www.westelm.com/products/candlewick-duvet-cover-shams-b2574/"
      },
      "priceRange":{  
        "selling":{  
          "high":199,
          "low":34
        }
      },
      "thumbnail":{  
        "size":"m",
        "meta":"",
        "alt":"",
        "rel":"thumbnail",
        "width":363,
        "href":"https://www.westelm.com/weimgs/rk/images/wcm/products/201843/0007/candlewick-duvet-cover-shams-1-m.jpg",
        "height":363
      },
      "hero":{  
        "size":"m",
        "meta":"",
        "alt":"",
        "rel":"hero",
        "width":363,
        "href":"https://www.westelm.com/weimgs/rk/images/wcm/products/201843/0007/candlewick-duvet-cover-shams-1-m.jpg",
        "height":363
      },
      "images":[  
        {  
          "size":"m",
          "meta":"",
          "alt":"",
          "rel":"althero",
          "width":363,
          "href":"https://www.westelm.com/weimgs/rk/images/wcm/products/201843/0007/candlewick-duvet-cover-shams-m.jpg",
          "height":363
        }
      ],
      "swatches":[  

      ],
      "messages":[  
        "Use Code SAVEMORE At Checkout"
      ],
      "flags":[  
        {  
          "bopisSuppress":false,
          "rank":3,
          "id":"newcore"
        },
        {  
          "bopisSuppress":false,
          "rank":4,
          "id":"freeship"
        },
        {  
          "bopisSuppress":false,
          "rank":7,
          "id":"organic"
        },
        {  
          "bopisSuppress":false,
          "rank":9,
          "id":"fairTrade"
        }
      ],
      "reviews":{  
        "recommendationCount":0,
        "likelihood":0,
        "reviewCount":0,
        "averageRating":0,
        "id":"candlewick-duvet-cover-shams-b2574",
        "type":"GROUP_REVIEWS"
      }
    },
    {  
      "id":"organic-washed-cotton-stripe-duvet-shams-vintage-rose-b2576",
      "name":"Organic Washed Cotton Stripe Duvet Cover + Shams - Vintage Rose",
      "links":{  
        "www":"https://www.westelm.com/products/organic-washed-cotton-stripe-duvet-shams-vintage-rose-b2576/"
      },
      "priceRange":{  
        "selling":{  
          "high":159,
          "low":34
        }
      },
      "thumbnail":{  
        "size":"m",
        "meta":"",
        "alt":"",
        "rel":"thumbnail",
        "width":363,
        "href":"https://www.westelm.com/weimgs/rk/images/wcm/products/201845/0009/organic-washed-cotton-stripe-duvet-cover-shams-vintage-ros-2-m.jpg",
        "height":363
      },
      "hero":{  
        "size":"m",
        "meta":"",
        "alt":"",
        "rel":"hero",
        "width":363,
        "href":"https://www.westelm.com/weimgs/rk/images/wcm/products/201845/0009/organic-washed-cotton-stripe-duvet-cover-shams-vintage-ros-2-m.jpg",
        "height":363
      },
      "images":[  
        {  
          "size":"m",
          "meta":"",
          "alt":"",
          "rel":"althero",
          "width":363,
          "href":"https://www.westelm.com/weimgs/rk/images/wcm/products/201845/0009/organic-washed-cotton-stripe-duvet-cover-shams-vintage-ros-m.jpg",
          "height":363
        },
        {  
          "size":"m",
          "meta":"",
          "alt":"",
          "rel":"althero",
          "width":363,
          "href":"https://www.westelm.com/weimgs/rk/images/wcm/products/201845/0009/organic-washed-cotton-stripe-duvet-cover-shams-vintage-ros-1-m.jpg",
          "height":363
        }
      ],
      "swatches":[  

      ],
      "messages":[  
        "Use Code SAVEMORE At Checkout"
      ],
      "flags":[  
        {  
          "bopisSuppress":false,
          "rank":3,
          "id":"newcore"
        },
        {  
          "bopisSuppress":false,
          "rank":4,
          "id":"freeship"
        },
        {  
          "bopisSuppress":false,
          "rank":11,
          "id":"new_colors"
        }
      ],
      "reviews":{  
        "recommendationCount":0,
        "likelihood":0,
        "reviewCount":0,
        "averageRating":0,
        "id":"organic-washed-cotton-stripe-duvet-shams-vintage-rose-b2576",
        "type":"GROUP_REVIEWS"
      }
    }
  ],
  "totalPages":52,
  "categories":[  

  ]
}
module.exports.Products = Products;